## initial list of manual builds in rpm-list-builder format (historical reasons)
## STEP 0: bump package version and set macros version to new python
#- python-rpm-macros
## build python3.N-1 together with python3.N without any bcond, verify python3.N-1 is nonmain python
#- python3.N:
#    macros:
#      %global _with_bootstrap 1  # bump the release so it's greater even with ~bootstrap
#- gdb: # not blocking (yet)
#    macros:
#      %global _without_python 1
#- python-flit-core::bootstrap:::
#    macros:
#      %global _with_bootstrap 1  # bump the release so it's greater even with ~bootstrap
#- python-packaging::bootstrap:::
#    macros:
#      %global _with_bootstrap 1  # bump the release so it's greater even with ~bootstrap
#- python-setuptools::bootstrap:::
#    macros:
#      %global _with_bootstrap 1  # bump the release so it's greater even with ~bootstrap
#- python-pip:man-tests::::
#    macros:
#      %global _without_tests 1
#      %global _without_man 1
#- pyparsing:  # python BuildRequires systemtap-sdt-devel Requires pyparsing
#    macros:
#      %global _without_tests 1
#      %global _without_doc 1
#      %global _without_extras 1
## wait for gdb
#- python3.N
# VERIFY all of the above have correct Provides/Requires
# do a test/scratch build to VERIFY python3-rpm-generators work before proceeding!

[koji]
# target = 'rawhide'
target = 'f45-python'
bootstrap_target = 'f45-python-bootstrap'

[distgit]
branch = "rawhide"
commit_message = "Rebuilt for Python 3.15"
bootstrap_commit_message = "Bootstrap for Python 3.15"
author = "Python Maint <python-maint@redhat.com>"

[architectures]
repoquery = "x86_64" # used for repository querying
koji = "x86_64" # used to scratch build packages with bconds

[deps]
old = ["python(abi) = 3.14", "libpython3.14.so.1.0()(64bit)", "libpython3.14d.so.1.0()(64bit)"]
new = ["python(abi) = 3.15", "libpython3.15.so.1.0()(64bit)", "libpython3.15d.so.1.0()(64bit)"]

[components]
excluded = ["python3.14", "python3.15", "kernel"]
extra = []

[cache_dir]
dnf = "_dnf_cache_dir"
fedpkg = "_fedpkg_cache_dir"

[repos]
[[repos.rawhide]]
repoid = "rawhide"
# metalink = "https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=$basearch"
baseurl = ["https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20260606.n.0/compose/Everything/$basearch/os/"]
metadata_expire = 600000000

[[repos.rawhide]]
repoid = "rawhide-source"
# metalink = "https://mirrors.fedoraproject.org/metalink?repo=rawhide-source&arch=$basearch"
baseurl = ["https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20260606.n.0/compose/Everything/source/tree/"]
metadata_expire = 600000000

[[repos.target]]
repoid = "f45-build"
baseurl = ["http://kojipkgs.fedoraproject.org/repos/f45-build/latest/$basearch/"]
metadata_expire = 60

# comment this section out to stop checking for prerel-abi
# [prerel]
# current_version = "3.15.0~beta1"

[bconds]
[[bconds.python-setuptools]]
withs = ["bootstrap"]

[[bconds.python-packaging]]
withs = ["bootstrap"]

[[bconds.python-pip]]
withouts = ["tests", "man"]

[[bconds.python-tomli-w]]
withouts = ["check"]

[[bconds.python-setuptools_scm]]
withouts = ["tests"]

[[bconds.python-py]]
withouts = ["docs", "tests"]

[[bconds.python-chardet]]
withouts = ["doc"]

[[bconds.python-pbr]]
withs = ["bootstrap"]
withouts = ["tests"]

[[bconds.python-extras]]
withs = ["bootstrap"]

[[bconds.python-testtools]]
withs = ["bootstrap"]

[[bconds.python-attrs]]
withouts = ["tests"]

[[bconds.python-pluggy]]
withouts = ["tests"]

[[bconds.python-sortedcontainers]]
withouts = ["docs", "tests"]

[[bconds.python-hypothesis]]
withouts = ["doc", "tests"]

[[bconds.python-hypothesmith]]
withouts = ["tests"]

[[bconds.python-pygments]]
withouts = ["docs", "tests"]

[[bconds.python-filelock]]
withouts = ["docs", "tests"]

[[bconds.python-elementpath]]
withouts = ["tests"]

[[bconds.python-iniconfig]]
withouts = ["tests"]

[[bconds.Cython]]
withouts = ["tests"]

[[bconds.python-more-itertools]]
withouts = ["tests"]

[[bconds.python-fixtures]]
withs = ["bootstrap"]

[[bconds.python-wcwidth]]
withouts = ["tests"]

[[bconds.pytest]]
withouts = ["timeout", "tests", "docs"]

[[bconds.python-virtualenv]]
withs = ["bootstrap"]

[[bconds.babel]]
withs = ["bootstrap"]

[[bconds.python-jinja2]]
withouts = ["docs", "asyncio_tests"]

[[bconds.python-sphinx_rtd_theme]]
withs = ["bootstrap"]

[[bconds.python-sphinx-basic-ng]]
withs = ["bootstrap"]

[[bconds.python-urllib3]]
withouts = ["tests", "extradeps"]

[[bconds.python-requests]]
withouts = ["tests"]

[[bconds.python-sphinx]]
withouts = ["tests", "sphinxcontrib"]

[[bconds.python-jedi]]
withouts = ["tests"]

[[bconds.python-dateutil]]
withouts = ["tests"]

[[bconds.python-jsonschema]]
withouts = ["tests"]

[[bconds.python-sphinxcontrib-websupport]]
withouts = ["optional_tests"]

[[bconds.python-soupsieve]]
withouts = ["tests"]

[[bconds.python-pytest-asyncio]]
withouts = ["tests"]

[[bconds.python-pytest-cov]]
withouts = ["tests"]

[[bconds.python-flit-core]]
withs = ["bootstrap"]

[[bconds.python-async-timeout]]
withouts = ["tests"]

[[bconds.python-jupyter-client]]
withs = ["bootstrap"]

[[bconds.python-jupyter-server]]
withs = ["bootstrap"]

[[bconds.python-matplotlib]]
withouts = ["check"]

[[bconds.ipython]]
withouts = ["check","doc"]

[[bconds.python-ipykernel]]
withs = ["bootstrap"]

[[bconds.pybind11]]
withouts = ["optional_tests"]

[[bconds.python-nbconvert]]
withouts = ["check", "doc"]

[[bconds.python-nbclient]]
withs = ["bootstrap"]

[[bconds.python-pyquery]]
withouts = ["tests"]

[[bconds.python-cherrypy]]
withouts = ["tests"]

[[bconds.freeipa-healthcheck]]
withouts = ["tests"]

[[bconds.python-Traits]]
withs = ["bootstrap"]

[[bconds.python-pcodedmp]]
withs = ["bootstrap"]

[[bconds.python-libcst]]
withs = ["bootstrap"]

[[bconds.scipy]]
withouts = ["pythran", "pooch", "tests"]

[[bconds.python-pandas]]
withs = ["bootstrap"]

[[bconds.python-fasteners]]
withouts = ["tests"]

[[bconds.python-zope-event]]
withs = ["bootstrap"]
withouts = ["docs"]

[[bconds.python-zope-interface]]
withouts = ["docs"]

[[bconds.python-tqdm]]
withouts = ["tests"]

[[bconds.python-cryptography]]
withouts = ["tests"]

[[bconds.python-decopatch]]
withouts = ["tests"]

[[bconds.python-geopandas]]
withs = ["bootstrap"]

[[bconds.python-astropy]]
withouts = ["check"]

[[bconds.python-pyerfa]]
withouts = ["tests"]

[[bconds.python-aiohttp]]
withouts = ["tests"]

[[bconds.python-azure-core]]
withouts = ["tests"]

# this bcond is disabled in spec on purpose
# it might be enabled in the future, so leaving this here, commend out
#[[bconds.python-azure-common]]
#withouts = ["tests"]

[[bconds.python-subprocess-tee]]
withouts = ["tests"]

[[bconds.python-typeguard]]
withs = ["bootstrap"]

[[bconds.python-tox]]
withs = ["bootstrap"]

[[bconds.python-fsspec]]
withs = ["bootstrap"]

[[bconds.python-pyface]]
withs = ["bootstrap"]

[[bconds.python-contourpy]]
withs = ["bootstrap"]

[[bconds.python-msrest]]
withouts = ["tests"]

[[bconds.python-oletools]]
withs = ["bootstrap"]

[[bconds.python-google-api-core]]
withouts = ["tests"]

[[bconds.fonttools]]
withouts = ["tests", "plot_extra", "symfont_extra", "ufo_extra", "woff_extra", "graphite_extra", "interpolatable_extra"]

[[bconds.conda]]
withs = ["bootstrap"]

[[bconds.python-conda-libmamba-solver]]
withouts = ["tests"]

[[bconds.python-conda-index]]
withs = ["bootstrap"]

[[bconds.python-conda-package-streaming]]
withs = ["bootstrap"]

[[bconds.python-googleapis-common-protos]]
withs = ["bootstrap"]

[[bconds.python-proto-plus]]
withouts = ["tests"]

[[bconds.python-dns]]
withouts = ["trio", "curio", "doh"]

[[bconds.python-beautifulsoup4]]
withouts = ["soupsieve", "tests"]

[[bconds.python-lxml]]
withouts = ["extras"]

[[bconds.python-constantly]]
withs = ["bootstrap"]

# this is intentionally commented out
# 1) is is part of the initial bootstrap
# 2) replacement does not work, the macro isn't there (needs to be added)
#[[bconds.gdb]]
#replacements = {_without_python = "1"}

[[bconds.python-pysocks]]
replacements = {with_python3_tests = "0"}

[[bconds.ara]]
replacements = {with_docs = "0"}

[[bconds.python-httpretty]]
replacements = {run_tests = "0"}

[[bconds.python-ruamel-yaml]]
withs = ["bootstrap"]

[[bconds.python-rq]]
withouts = ["tests"]

[[bconds.python-markdown-it-py]]
withouts = ["plugins"]

[[bconds.python-factory-boy]]
withouts = ["tests"]

[[bconds.python-tox-current-env]]
withs = ["bootstrap"]

[[bconds.python-pikepdf]]
withouts = ["docs", "tests"]

[[bconds.python-executing]]
withs = ["bootstrap"]

[[bconds.python-editables]]
withouts = ["doc"]

[[bconds.python-jsonschema-specifications]]
replacements = {with_doc = "0"}

[[bconds.python-openstackclient]]
withs = ["bootstrap"]

[[bconds.python-oslo-config]]
withs = ["bootstrap"]

[[bconds.python-neutronclient]]
replacements = {with_doc = "0"}

[[bconds.python-glanceclient]]
replacements = {with_doc = "0"}

[[bconds.python-domdf-python-tools]]
withouts = ["tests"]

[[bconds.python-tiny-proxy]]
withouts = ["tests"]

[[bconds.python-werkzeug]]
withouts = ["tests"]

[[bconds.python-netaddr]]
withouts = ["docs"]

[[bconds.python-dirty-equals]]
withs = ["bootstrap"]

[[bconds.python-snakemake-interface-storage-plugins]]
withs = ["bootstrap"]

[[bconds.python-snakemake-interface-executor-plugins]]
withs = ["bootstrap"]

[[bconds.python-snakemake-interface-report-plugins]]
withs = ["bootstrap"]

[[bconds.snakemake]]
withs = ["bootstrap"]

[[bconds.python-sphinx-theme-builder]]
withs = ["bootstrap"]

[[bconds.python-httpx]]
withouts = ["tests"]

[[bconds.python-pymssql]]
withouts = ["tests"]

[[bconds.python-authlib]]
withouts = ["tests"]

[[bconds.python-oslotest]]
withs = ["bootstrap"]

[[bconds.python-gunicorn]]
withouts = ["extras"]

[[bconds.python-execnet]]
withouts = ["optional_test_deps"]

[[bconds.python-threadpoolctl]]
withouts = ["check"]

[[bconds.python-tabulate]]
withs = ["bootstrap"]

[[bconds.python-repoze-sphinx-autointerface]]
withouts = ["tests"]

[[bconds.python-zope-exceptions]]
withouts = ["tests"]

[[bconds.python-deepdiff]]
withouts = ["tests"]

[[bconds.python-sentry-sdk]]
withouts = ["tests"]

[[bconds.python-dask]]
withs = ["bootstrap"]

[[bconds.python-build]]
withouts = ["extras"]

[[bconds.meson]]
withouts = ["check"]

[[bconds.python-gmpy2]]
withouts = ["tests"]

[[bconds.python-humanfriendly]]
withs = ["bootstrap"]

[[bconds.python-cascadio]]
withs = ["bootstrap"]

[[bconds.python-pint]]
withouts = ["xarray"]

[[bconds.python-qcengine]]
withouts = ["tests"]

[[bconds.python-astropy-iers-data]]
withouts = ["tests"]

[[bconds.python-pymongo]]
withs = ["bootstrap"]

[[bconds.python-pyogrio]]
withs = ["bootstrap"]

[[bconds.python-fastapi]]
withs = ["bootstrap"]

[[bconds.python-pydantic-core]]
withouts = ["inline_snapshot_tests"]

[[bconds.python-optking]]
withouts = ["tests"]

[[bconds.python-django5]]
withouts = ["tests"]

[[bconds.python-django6]]
withouts = ["tests"]

[[bconds.python-pyproject-hooks]]
withouts = ["tests"]

[[bconds.python-Automat]]
withouts = ["doc"]

[[bconds.python-psutil]]
withouts = ["xdist"]

[[bconds.python-apkinspector]]
withs = ["bootstrap"]

[[bconds.python-androguard]]
withs = ["bootstrap"]

[[bconds.python-service-identity]]
withouts = ["docs"]

[[bconds.mkdocs-material]]
withs = ["bootstrap"]

[[bconds.python-mkdocs-material-extensions]]
withouts = ["tests"]

[[bconds.python-zope-testing]]
withouts = ["tests"]

[[bconds.python-xnat]]
withs = ["bootstrap"]

[[bconds.python-tablib]]
withs = ["bootstrap"]

[[bconds.llvm]]
withouts = ["pgo"]

[[bconds.llvm21 ]]
withouts = ["pgo"]

[[bconds.python-pathspec]]
withouts = ["tests"]

[[bconds.python-hatch-vcs]]
withs = ["bootstrap"]

[[bconds.python-cobalt]]
withs = ["bootstrap"]

[[bconds.vtk]]
withs = ["bootstrap"]

[[bconds.python-trove-classifiers]]
withouts = ["tests"]

[[bconds.python-snakemake-interface-common]]
withs = ["bootstrap"]

[[bconds.python-snakemake-interface-scheduler-plugins]]
withs = ["bootstrap"]

[[bconds.python-snakemake-interface-logger-plugins]]
withs = ["bootstrap"]

[[bconds.python-azure-mgmt-core]]
withouts = ["tests"]

[[bconds.python-networkx]]
withs = ["bootstrap"]

[[bconds.python-questionary]]
withs = ["bootstrap"]

[[bconds.python-paste-deploy]]
withouts = ["tests"]

[[bconds.python-llm]]
withouts = ["tests"]

[[bconds.python-rjsmin]]
withouts = ["docs"]

[[bconds.python-webtest]]
withouts = ["tests"]

[[bconds.python-menuinst]]
withs = ["bootstrap"]

[[bconds.python-cliff]]
withs = ["bootstrap"]

[[bconds.python-stevedore]]
withs = ["bootstrap"]

[[bconds.python-vcs-versioning]]
withs = ["bootstrap"]

[[bconds.python-scikit-build-core]]
withouts = ["tests"]

[[bconds.pyproj]]
withouts = ["xarray"]

[[bconds.python-distlib]]
withouts = ["check"]

[[bconds.python-flit]]
withouts = ["tests"]

[[bconds.python-platformdirs]]
withouts = ["tests"]

[[bconds.python-jaraco-context]]
withouts = ["tests"]

[[bconds.ninja-build]]
withs = ["bootstrap"]

[[bconds.python-google-auth]]
withouts = ["grpcio", "tests"]

[[bconds.python-os-service-types]]
withs = ["bootstrap"]

[[bconds.python-poetry-core]]
withouts = ["tests"]

[[bconds.python-msal]]
withs = ["bootstrap"]

[[bconds.python-setuptools80]]
withs = ["bootstrap"]

[[bconds.python-versioningit]]
withouts = ["pydantic_tests"]

[[bconds.python-scikit-image]]
withouts = ["check"]

[[bconds.python-semantic_version]]
withs = ["bootstrap"]

[[bconds.python-httpx2]]
withs = ["bootstrap"]

[[bconds.python-trimesh]]
withs = ["bootstrap"]

[[bconds.python-scikit-image]]
withs = ["bootstrap"]

# [[bconds.OpenColorIO]]
# %global bootstrap 1
# we lack config syntax for that :(
